# Generated by Django 3.1.2 on 2020-11-22 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='description',
            new_name='desc',
        ),
    ]
