# Generated by Django 3.1.2 on 2020-11-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20201122_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumimage',
            name='desc',
            field=models.CharField(default='The author is so lazy that leave nothing!', max_length=300),
        ),
    ]
