# Generated by Django 3.1.2 on 2020-12-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_auto_20201127_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='thumb',
            field=models.ImageField(upload_to='covers'),
        ),
    ]
